mysite/mysite/core/urls.py
from django.urls import path

from mysite.core import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
    path('contato', views.contact, name='contact'),
]

mysite/mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('mysite.core.urls')),
    path('admin/', admin.site.urls),
]

mysite/mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/mysite/core/models.py
from django.db import models

# Create your models here.

mysite/mysite/cursos/models.py
from django.db import models

# Create your models here.

mysite/mysite/accounts/views.py
from django.shortcuts import render

# Create your views here.

mysite/mysite/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

mysite/mysite/cursos/views.py
from django.shortcuts import render

# Create your views here.

mysite/mysite/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>My Site</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">My Site</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="">Cursos</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="">Painel</a></li>
            <li><a href="">Sair</a></li>
            {% else %}
            <li><a href="">Entrar</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        My Site - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

mysite/mysite/core/templates/contact.html
{% extends "base.html" %}


{% block content %}
    
    
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1>Fale conosco</h1>
            <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
            <h4>Links</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@mysite.com.br">contato@mysite.com.br</a></li>
                <li>Twitter: <a href="https://twitter.com/mysite">@mysite</a></li>
            </ul>
        </div>
    </div>
{% endblock content %}

mysite/mysite/core/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância
                    </h1>
                    <h2 class="splash-subhead">
                        O My Site visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                <h3>Publique suas aulas</h3>
                <p>
                    O My Site tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                </p>
            </div>
        </div>
        <div class="pure-u-1-3">
            <div class="l-box">
                <img src="http://placehold.it/400x250"
                     alt="Vídeo aulas e materiais digitais.">
            </div>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1-3">
            <div class="l-box">
                <img src="http://placehold.it/400x250"
                     alt="Fórum de Dúvidas">
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Fórum de Dúvidas</h4>
                <h3>Interaja com seus Alunos</h3>
                <p>
                    No My Site você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                </p>
            </div>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Exercícios</h4>
                <h3>Crie exercícios para avaliar seus alunos</h3>
                <p>
                    Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                </p>
            </div>
        </div>
        <div class="pure-u-1-3">
            <div class="l-box">
                <img src="http://placehold.it/400x250"
                     alt="Exercícios">
            </div>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1-3">
            <div class="l-box">
                <img src="http://placehold.it/400x250"
                     alt="Mural de Avisos">
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Mural de Avisos</h4>
                <h3>Envie anúncios diretamente para os alunos</h3>
                <p>
                    Organize os avisos do seu curso de forma fácil e simples.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

mysite/mysite/cursos/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
<div class="well">
    <h2>Iníco das aulas, sejam bem vindos</h2>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <p>
        <a href="#comments" title="">
        <i class="fa fa-comments-o"></i>
        10 Comentários
        </a>
    </p>
</div>
<div class="well">
    <h2>Iníco das aulas, sejam bem vindos</h2>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <p>
        <a href="#comments" title="">
        <i class="fa fa-comments-o"></i>
        10 Comentários
        </a>
    </p>
</div>
{% endblock %}

mysite/mysite/cursos/templates/courses/contact_email.html
<p><strong>Nome</strong>:{{ name }}</p>
<p><strong>E-mail</strong>:{{ email }}</p>
{{ message|linebreaks }}

mysite/mysite/cursos/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
{% endblock %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="#">
        <i class="fa fa-video-camera"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

mysite/mysite/cursos/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon" id="contato">
    <div class="pure-u-1">
        <h3>Tire sua dúvida sobre o Curso</h3>
        {% if is_valid %}
        <p>Você enviou o formulário com sucesso</p>
        {% endif %}
        <form action="#contato" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

mysite/mysite/cursos/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>

                {{ course.description|linebreaks }}

        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mysite/mysite/cursos/templates/courses/templatetags/my_courses.html
<li class="pure-menu-heading">Meus Cursos</li>
{% for enrollment in enrollments %}
<li><a href="#">{{ enrollment.course }}</a></li>
{% empty %}
<li>Nenhum curso encontrado</li>
{% endfor %}

mysite/mysite/cursos/templates/courses/undo_enrollment.html
{% extends 'courses/course_dashboard.html' %}

{% block dashboard_content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
    <div class="pure-controls">
        <button type="submit" class="pure-button pure-button-primary">Confirmar</button>
        <a href="{% url 'courses:announcements' course.slug %}" class="pure-button">Voltar</a>
    </div>
</form>
{% endblock %}